// DF Materials Matrix — universal 1-5 scoring. Weights: {"performance": 1.5, "lightness": 1.5, "cost": 1.0, "workability": 1.0, "durability": 1.2, "health": 1.2, "sustainability": 0.8}
window.MATRIX_AXES=["performance", "lightness", "cost", "workability", "durability", "health", "sustainability"];
window.MATRIX_WEIGHTS={"performance": 1.5, "lightness": 1.5, "cost": 1.0, "workability": 1.0, "durability": 1.2, "health": 1.2, "sustainability": 0.8};
window.MATERIALS=[
  {
    "id": "glass-laminated",
    "name": "Laminated safety glass",
    "category": "glazing",
    "scores": {
      "performance": 5,
      "lightness": 1,
      "cost": 3,
      "workability": 1,
      "durability": 4,
      "health": 5,
      "sustainability": 3
    },
    "weighted": 3.2,
    "perf_metric": "clarity 90%, holds together cracked",
    "weight_note": "2.5 g/cm3",
    "cost_note": "mid",
    "pros": "optical clarity for DRIVING, scratch-proof, FMVSS windshield",
    "cons": "heaviest, OEM-only",
    "status": "REQUIRED windshield",
    "spec_strength_kNmkg": null,
    "cost_per_kg_usd": null,
    "use": "windshield"
  },
  {
    "id": "glass-tempered",
    "name": "Tempered glass",
    "category": "glazing",
    "scores": {
      "performance": 4,
      "lightness": 1,
      "cost": 4,
      "workability": 2,
      "durability": 3,
      "health": 5,
      "sustainability": 4
    },
    "weighted": 3.21,
    "perf_metric": "clarity 90%; shatters (safe crumble)",
    "weight_note": "2.5 g/cm3",
    "cost_note": "cheap",
    "pros": "cheapest, scratch-proof, inert",
    "cons": "heavy, shatters",
    "status": "reference",
    "spec_strength_kNmkg": null,
    "cost_per_kg_usd": null,
    "use": "\u2014"
  },
  {
    "id": "acrylic-dualpane",
    "name": "Acrylic (PMMA) dual-pane",
    "category": "glazing",
    "scores": {
      "performance": 5,
      "lightness": 4,
      "cost": 3,
      "workability": 4,
      "durability": 3,
      "health": 4,
      "sustainability": 3
    },
    "weighted": 3.82,
    "perf_metric": "clearest 92%, dual-pane insulates, UV-stable",
    "weight_note": "~1.18 g/cm3 (~40% of glass)",
    "cost_note": "mid",
    "pros": "RECO living windows: lightest+clearest+no-shatter+UV-stable",
    "cons": "scratches if cleaned wrong",
    "status": "RECO living-area",
    "spec_strength_kNmkg": null,
    "cost_per_kg_usd": null,
    "use": "living windows"
  },
  {
    "id": "polycarbonate",
    "name": "Polycarbonate (PC / Lexan)",
    "category": "glazing",
    "scores": {
      "performance": 3,
      "lightness": 4,
      "cost": 2,
      "workability": 4,
      "durability": 5,
      "health": 4,
      "sustainability": 3
    },
    "weighted": 3.62,
    "perf_metric": "88-90% light; yellows w/o UV coat",
    "weight_note": "~1.2 g/cm3",
    "cost_note": "higher",
    "pros": "IMPACT ~250x glass, cold-forms",
    "cons": "scratches, yellows w/o coat",
    "status": "impact zones",
    "spec_strength_kNmkg": null,
    "cost_per_kg_usd": null,
    "use": "skylight/impact"
  },
  {
    "id": "vacuum-glazing",
    "name": "Vacuum glazing (thin high-R glass)",
    "category": "glazing",
    "scores": {
      "performance": 5,
      "lightness": 2,
      "cost": 1,
      "workability": 1,
      "durability": 2,
      "health": 5,
      "sustainability": 3
    },
    "weighted": 2.84,
    "perf_metric": "very high insulation in a slim clear pane",
    "weight_note": "glass (heavy)",
    "cost_note": "very $$$",
    "pros": "thin+high-R+clear",
    "cons": "fragile edge-seal, custom",
    "status": "premium/niche",
    "spec_strength_kNmkg": null,
    "cost_per_kg_usd": null,
    "use": "niche"
  },
  {
    "id": "etfe-film",
    "name": "ETFE film cushion",
    "category": "glazing",
    "scores": {
      "performance": 2,
      "lightness": 5,
      "cost": 3,
      "workability": 3,
      "durability": 3,
      "health": 4,
      "sustainability": 4
    },
    "weighted": 3.43,
    "perf_metric": "translucent, insulating cushion",
    "weight_note": "near-zero",
    "cost_note": "mid",
    "pros": "ultralight, self-clean skylights",
    "cons": "not a clear view window",
    "status": "niche skylight",
    "spec_strength_kNmkg": null,
    "cost_per_kg_usd": null,
    "use": "skylight"
  },
  {
    "id": "mild-steel",
    "name": "Mild steel (A36)",
    "category": "structural",
    "scores": {
      "performance": 3,
      "lightness": 1,
      "cost": 5,
      "workability": 4,
      "durability": 4,
      "health": 5,
      "sustainability": 4
    },
    "weighted": 3.54,
    "perf_metric": "yield ~250 MPa; cheap+strong but heavy",
    "weight_note": "7.85 g/cm3 (heaviest)",
    "cost_note": "~$1/kg",
    "pros": "cheapest, weld/cut anywhere, inert, recyclable",
    "cons": "heavy, rusts (needs coat), low specific strength",
    "status": "reference / brackets",
    "spec_strength_kNmkg": 32,
    "cost_per_kg_usd": 1.0,
    "use": "brackets, subframe"
  },
  {
    "id": "uhss",
    "name": "UHSS / AHSS (crash)",
    "category": "structural",
    "scores": {
      "performance": 5,
      "lightness": 1,
      "cost": 4,
      "workability": 2,
      "durability": 5,
      "health": 5,
      "sustainability": 4
    },
    "weighted": 3.68,
    "perf_metric": "yield ~1000-1500 MPa; crash structure",
    "weight_note": "7.85 g/cm3",
    "cost_note": "~$2/kg",
    "pros": "strongest, crash/impact structure, cheap-ish",
    "cons": "heavy, hard to form/weld (press), rusts",
    "status": "rocker + crash zones",
    "spec_strength_kNmkg": 153,
    "cost_per_kg_usd": 2.0,
    "use": "rocker, crush zones"
  },
  {
    "id": "ss-316l",
    "name": "Stainless 316L",
    "category": "structural",
    "scores": {
      "performance": 4,
      "lightness": 1,
      "cost": 2,
      "workability": 3,
      "durability": 5,
      "health": 5,
      "sustainability": 4
    },
    "weighted": 3.38,
    "perf_metric": "yield ~250 MPa; corrosion + food-safe",
    "weight_note": "8.0 g/cm3",
    "cost_note": "~$6/kg",
    "pros": "corrosion-proof, food-safe \u2192 WET trays; inert",
    "cons": "heavy, pricey",
    "status": "wet trays / hydro",
    "spec_strength_kNmkg": 31,
    "cost_per_kg_usd": 6.0,
    "use": "wet trays, tanks"
  },
  {
    "id": "al-6063",
    "name": "Aluminium 6063 extrusion",
    "category": "structural",
    "scores": {
      "performance": 4,
      "lightness": 4,
      "cost": 4,
      "workability": 5,
      "durability": 4,
      "health": 5,
      "sustainability": 4
    },
    "weighted": 4.27,
    "perf_metric": "yield ~215 MPa; easy-extrude T-slot",
    "weight_note": "2.70 g/cm3",
    "cost_note": "~$3.5/kg",
    "pros": "RECO dry frame: extrude/T-slot/cut/join easy, corrosion-safe, recyclable",
    "cons": "conducts heat (thermal bridge); softer",
    "status": "RECO dry frame",
    "spec_strength_kNmkg": 80,
    "cost_per_kg_usd": 3.5,
    "use": "dry frame, slides"
  },
  {
    "id": "al-6061",
    "name": "Aluminium 6061-T6",
    "category": "structural",
    "scores": {
      "performance": 4,
      "lightness": 4,
      "cost": 3,
      "workability": 4,
      "durability": 4,
      "health": 5,
      "sustainability": 4
    },
    "weighted": 4.02,
    "perf_metric": "yield ~276 MPa; general structural",
    "weight_note": "2.70 g/cm3",
    "cost_note": "~$4/kg",
    "pros": "strong, weldable/machinable, corrosion-safe",
    "cons": "thermal bridge",
    "status": "structural members",
    "spec_strength_kNmkg": 102,
    "cost_per_kg_usd": 4.0,
    "use": "structural members"
  },
  {
    "id": "al-7075",
    "name": "Aluminium 7075-T6",
    "category": "structural",
    "scores": {
      "performance": 5,
      "lightness": 4,
      "cost": 2,
      "workability": 3,
      "durability": 3,
      "health": 5,
      "sustainability": 4
    },
    "weighted": 3.82,
    "perf_metric": "yield ~500 MPa; aerospace-grade Al",
    "weight_note": "2.81 g/cm3",
    "cost_note": "~$6/kg",
    "pros": "near-steel strength at 1/3 weight",
    "cons": "pricey, not readily weldable, stress-corrosion",
    "status": "high-load fittings",
    "spec_strength_kNmkg": 178,
    "cost_per_kg_usd": 6.0,
    "use": "high-load fittings"
  },
  {
    "id": "magnesium",
    "name": "Magnesium alloy (AZ31)",
    "category": "structural",
    "scores": {
      "performance": 3,
      "lightness": 5,
      "cost": 3,
      "workability": 3,
      "durability": 2,
      "health": 4,
      "sustainability": 3
    },
    "weighted": 3.37,
    "perf_metric": "yield ~200 MPa; lightest structural metal",
    "weight_note": "1.77 g/cm3 (33% < Al)",
    "cost_note": "~$5/kg",
    "pros": "lightest metal, good stiffness/weight",
    "cons": "corrosion + flammable swarf; galvanic issues",
    "status": "niche weight-critical",
    "spec_strength_kNmkg": 113,
    "cost_per_kg_usd": 5.0,
    "use": "niche"
  },
  {
    "id": "titanium",
    "name": "Titanium (Ti-6Al-4V)",
    "category": "structural",
    "scores": {
      "performance": 5,
      "lightness": 3,
      "cost": 1,
      "workability": 2,
      "durability": 5,
      "health": 5,
      "sustainability": 3
    },
    "weighted": 3.59,
    "perf_metric": "yield ~880 MPa; ~2x Al specific strength",
    "weight_note": "4.43 g/cm3",
    "cost_note": "~$40/kg",
    "pros": "excellent specific strength + corrosion-proof",
    "cons": "very costly, hard to machine/weld",
    "status": "fasteners/niche only",
    "spec_strength_kNmkg": 199,
    "cost_per_kg_usd": 40.0,
    "use": "fasteners/niche"
  },
  {
    "id": "cfrp",
    "name": "Carbon fibre (CFRP)",
    "category": "structural",
    "scores": {
      "performance": 5,
      "lightness": 5,
      "cost": 1,
      "workability": 2,
      "durability": 4,
      "health": 3,
      "sustainability": 2
    },
    "weighted": 3.41,
    "perf_metric": "best strength-to-weight of all (layup)",
    "weight_note": "~1.6 g/cm3",
    "cost_note": "~$30/kg",
    "pros": "lightest+stiffest by far",
    "cons": "VERY costly, layup skill, hard repair, BRITTLE/hazardous failure",
    "status": "spaceship material \u2014 sparing use",
    "spec_strength_kNmkg": 625,
    "cost_per_kg_usd": 30.0,
    "use": "sparing / hardpoints"
  },
  {
    "id": "gfrp",
    "name": "Fiberglass (GFRP)",
    "category": "structural",
    "scores": {
      "performance": 4,
      "lightness": 4,
      "cost": 3,
      "workability": 3,
      "durability": 4,
      "health": 3,
      "sustainability": 2
    },
    "weighted": 3.41,
    "perf_metric": "tensile ~200-400 MPa; moldable skins",
    "weight_note": "~1.9 g/cm3",
    "cost_note": "~$4/kg",
    "pros": "light, moldable, corrosion-proof, tough",
    "cons": "resin health/recycle, harder repair",
    "status": "skins / molded parts",
    "spec_strength_kNmkg": 158,
    "cost_per_kg_usd": 4.0,
    "use": "skins, molded parts"
  },
  {
    "id": "flax-nfc",
    "name": "Flax / hemp composite (NFC)",
    "category": "structural",
    "scores": {
      "performance": 3,
      "lightness": 4,
      "cost": 3,
      "workability": 3,
      "durability": 3,
      "health": 4,
      "sustainability": 5
    },
    "weighted": 3.52,
    "perf_metric": "moderate strength; bio-composite",
    "weight_note": "~1.35 g/cm3",
    "cost_note": "~$7/kg",
    "pros": "renewable, biodegradable-ish, bio-resin options, damping",
    "cons": "moderate strength, moisture, niche supply",
    "status": "sustainable panels",
    "spec_strength_kNmkg": 111,
    "cost_per_kg_usd": 7.0,
    "use": "eco panels"
  },
  {
    "id": "al-honeycomb",
    "name": "Aluminium honeycomb sandwich",
    "category": "structural",
    "scores": {
      "performance": 5,
      "lightness": 5,
      "cost": 3,
      "workability": 3,
      "durability": 4,
      "health": 4,
      "sustainability": 3
    },
    "weighted": 4.02,
    "perf_metric": "excellent bending stiffness-to-weight (flat)",
    "weight_note": "very light core",
    "cost_note": "~$12/kg-eq",
    "pros": "stiff+ultralight FLAT panels (floor/walls)",
    "cons": "edge sealing + point loads tricky, cost",
    "status": "RECO floor/wall panels",
    "spec_strength_kNmkg": null,
    "cost_per_kg_usd": null,
    "use": "floors, wall panels"
  },
  {
    "id": "coosa",
    "name": "Coosa board (PU+fiberglass)",
    "category": "structural",
    "scores": {
      "performance": 3,
      "lightness": 4,
      "cost": 2,
      "workability": 4,
      "durability": 5,
      "health": 4,
      "sustainability": 2
    },
    "weighted": 3.52,
    "perf_metric": "substrate: 40-60% lighter than ply, 2-3x insul",
    "weight_note": "~half plywood",
    "cost_note": "~$330/0.5in sheet",
    "pros": "never rots/absorbs water, screws like wood, cuts easy",
    "cons": "pricey (~$330/sheet), substrate not primary structure",
    "status": "RECO cabinetry/wet substrate",
    "spec_strength_kNmkg": null,
    "cost_per_kg_usd": null,
    "use": "cabinetry, wet substrate"
  },
  {
    "id": "marine-ply",
    "name": "Marine / Baltic birch plywood",
    "category": "structural",
    "scores": {
      "performance": 3,
      "lightness": 2,
      "cost": 4,
      "workability": 5,
      "durability": 2,
      "health": 4,
      "sustainability": 4
    },
    "weighted": 3.28,
    "perf_metric": "cheap workable structural sheet",
    "weight_note": "~0.65 g/cm3 but thick",
    "cost_note": "~$2/kg",
    "pros": "cheapest, easiest DIY (screw/glue), low-VOC options",
    "cons": "heavy per strength, rot/moisture/delam risk",
    "status": "budget cabinetry",
    "spec_strength_kNmkg": 62,
    "cost_per_kg_usd": 2.0,
    "use": "budget cabinetry"
  },
  {
    "id": "bamboo-ply",
    "name": "Bamboo ply",
    "category": "structural",
    "scores": {
      "performance": 3,
      "lightness": 3,
      "cost": 3,
      "workability": 4,
      "durability": 3,
      "health": 4,
      "sustainability": 5
    },
    "weighted": 3.46,
    "perf_metric": "hard, dense sheet good",
    "weight_note": "~0.7 g/cm3",
    "cost_note": "~$3/kg",
    "pros": "fast-renewable, hard, attractive",
    "cons": "heavier, moisture, availability",
    "status": "eco surfaces",
    "spec_strength_kNmkg": null,
    "cost_per_kg_usd": null,
    "use": "eco surfaces"
  }
];
