// House BUS insulation materials DATABASE. Edit here; the viewer + configurator read it.
window.INSULATION = [
  {
    "name": "Sheep wool",
    "category": "natural",
    "r_per_in": 3.6,
    "density_kgm3": 20,
    "cost_per_bf_usd": 2.0,
    "thickness_in_R20": 5.56,
    "thickness_mm_R20": 141,
    "cost_R20_per_m2_usd": 120,
    "non_toxic": "yes",
    "foam": "no",
    "puncture": "none \u2014 resilient",
    "cuttability": "easy",
    "conform": "yes (drapes)",
    "thermal_bridging": "ok (can settle)",
    "fire": "self-extinguish",
    "moisture": "buffers moisture",
    "pros": "non-toxic, moisture-buffering, great acoustic",
    "cons": "thick, pricey, needs pest treatment"
  },
  {
    "name": "Hemp batt",
    "category": "natural",
    "r_per_in": 3.6,
    "density_kgm3": 35,
    "cost_per_bf_usd": 2.2,
    "thickness_in_R20": 5.56,
    "thickness_mm_R20": 141,
    "cost_R20_per_m2_usd": 132,
    "non_toxic": "yes",
    "foam": "no",
    "puncture": "none",
    "cuttability": "easy",
    "conform": "yes",
    "thermal_bridging": "ok",
    "fire": "treated",
    "moisture": "breathable",
    "pros": "non-toxic, carbon-negative, healthy",
    "cons": "thick, pricey, availability"
  },
  {
    "name": "Cotton / denim (recycled)",
    "category": "natural",
    "r_per_in": 3.6,
    "density_kgm3": 25,
    "cost_per_bf_usd": 1.2,
    "thickness_in_R20": 5.56,
    "thickness_mm_R20": 141,
    "cost_R20_per_m2_usd": 72,
    "non_toxic": "yes",
    "foam": "no",
    "puncture": "none",
    "cuttability": "medium (dense)",
    "conform": "semi",
    "thermal_bridging": "ok",
    "fire": "treated",
    "moisture": "holds moisture",
    "pros": "recycled, non-itch, acoustic",
    "cons": "thick, holds water if wet"
  },
  {
    "name": "Cellulose (dense-pack)",
    "category": "natural",
    "r_per_in": 3.5,
    "density_kgm3": 55,
    "cost_per_bf_usd": 0.5,
    "thickness_in_R20": 5.71,
    "thickness_mm_R20": 145,
    "cost_R20_per_m2_usd": 31,
    "non_toxic": "yes",
    "foam": "no",
    "puncture": "none",
    "cuttability": "n/a (loose fill)",
    "conform": "fills cavities",
    "thermal_bridging": "good (fills gaps)",
    "fire": "borate-treated",
    "moisture": "holds moisture",
    "pros": "cheap, fills odd gaps, eco",
    "cons": "SETTLES with vibration \u2014 poor for a vehicle; messy"
  },
  {
    "name": "Cork (expanded)",
    "category": "natural",
    "r_per_in": 3.8,
    "density_kgm3": 120,
    "cost_per_bf_usd": 4.0,
    "thickness_in_R20": 5.26,
    "thickness_mm_R20": 134,
    "cost_R20_per_m2_usd": 227,
    "non_toxic": "yes",
    "foam": "no",
    "puncture": "resistant",
    "cuttability": "easy",
    "conform": "semi (rigid)",
    "thermal_bridging": "good",
    "fire": "good",
    "moisture": "handles moisture",
    "pros": "natural, durable, moisture-safe",
    "cons": "thick, pricey, dense/heavy"
  },
  {
    "name": "Wood fibre (Gutex)",
    "category": "natural",
    "r_per_in": 3.7,
    "density_kgm3": 150,
    "cost_per_bf_usd": 1.5,
    "thickness_in_R20": 5.41,
    "thickness_mm_R20": 137,
    "cost_R20_per_m2_usd": 87,
    "non_toxic": "yes",
    "foam": "no",
    "puncture": "resistant",
    "cuttability": "easy",
    "conform": "no (board)",
    "thermal_bridging": "good",
    "fire": "char",
    "moisture": "breathable",
    "pros": "natural, acoustic, breathable",
    "cons": "thick, heavy"
  },
  {
    "name": "Fiberglass batt",
    "category": "mineral",
    "r_per_in": 3.2,
    "density_kgm3": 12,
    "cost_per_bf_usd": 0.4,
    "thickness_in_R20": 6.25,
    "thickness_mm_R20": 159,
    "cost_R20_per_m2_usd": 27,
    "non_toxic": "low (itchy dust)",
    "foam": "no",
    "puncture": "none",
    "cuttability": "easy",
    "conform": "semi",
    "thermal_bridging": "ok (compresses at studs)",
    "fire": "good",
    "moisture": "holds water (bad wet)",
    "pros": "cheapest, light, everywhere",
    "cons": "itchy, settles/sags with vibration, poor if damp"
  },
  {
    "name": "Mineral / rock wool (Rockwool)",
    "category": "mineral",
    "r_per_in": 4.0,
    "density_kgm3": 70,
    "cost_per_bf_usd": 1.0,
    "thickness_in_R20": 5.0,
    "thickness_mm_R20": 127,
    "cost_R20_per_m2_usd": 54,
    "non_toxic": "yes-ish (fibre)",
    "foam": "no",
    "puncture": "none",
    "cuttability": "easy (knife)",
    "conform": "semi (friction-fit)",
    "thermal_bridging": "good (dense)",
    "fire": "EXCELLENT (non-combustible ~1000C)",
    "moisture": "hydrophobic, dries",
    "pros": "fireproof, soundproof, water-shedding, holds shape",
    "cons": "heavier, thick \u2014 but a strong non-toxic vehicle option"
  },
  {
    "name": "Glass wool",
    "category": "mineral",
    "r_per_in": 3.3,
    "density_kgm3": 15,
    "cost_per_bf_usd": 0.5,
    "thickness_in_R20": 6.06,
    "thickness_mm_R20": 154,
    "cost_R20_per_m2_usd": 33,
    "non_toxic": "low (dust)",
    "foam": "no",
    "puncture": "none",
    "cuttability": "easy",
    "conform": "semi",
    "thermal_bridging": "ok",
    "fire": "good",
    "moisture": "holds water",
    "pros": "cheap, light",
    "cons": "itchy, damp-sensitive"
  },
  {
    "name": "Cellular glass (Foamglas)",
    "category": "mineral",
    "r_per_in": 3.2,
    "density_kgm3": 120,
    "cost_per_bf_usd": 3.0,
    "thickness_in_R20": 6.25,
    "thickness_mm_R20": 159,
    "cost_R20_per_m2_usd": 202,
    "non_toxic": "yes",
    "foam": "no",
    "puncture": "resistant (rigid)",
    "cuttability": "hard (brittle, saw)",
    "conform": "no",
    "thermal_bridging": "good",
    "fire": "excellent",
    "moisture": "WATERPROOF (impermeable)",
    "pros": "waterproof, incompressible, vermin/fire-proof",
    "cons": "brittle, heavy, pricey, low R"
  },
  {
    "name": "EPS",
    "category": "foam",
    "r_per_in": 3.9,
    "density_kgm3": 20,
    "cost_per_bf_usd": 0.3,
    "thickness_in_R20": 5.13,
    "thickness_mm_R20": 130,
    "cost_R20_per_m2_usd": 17,
    "non_toxic": "low",
    "foam": "YES",
    "puncture": "some (crumbles)",
    "cuttability": "easy (hot-wire)",
    "conform": "no",
    "thermal_bridging": "edge-ok",
    "fire": "poor (needs cover)",
    "moisture": "absorbs some",
    "pros": "cheapest per R, light",
    "cons": "foam, low-R, vapor issues"
  },
  {
    "name": "Graphite-EPS (Neopor)",
    "category": "foam",
    "r_per_in": 4.7,
    "density_kgm3": 18,
    "cost_per_bf_usd": 0.65,
    "thickness_in_R20": 4.26,
    "thickness_mm_R20": 108,
    "cost_R20_per_m2_usd": 30,
    "non_toxic": "low",
    "foam": "YES",
    "puncture": "some",
    "cuttability": "easy",
    "conform": "no",
    "thermal_bridging": "edge-ok",
    "fire": "poor",
    "moisture": "absorbs some",
    "pros": "cheap, better R than EPS",
    "cons": "foam, needs fire cover"
  },
  {
    "name": "XPS",
    "category": "foam",
    "r_per_in": 4.7,
    "density_kgm3": 30,
    "cost_per_bf_usd": 0.55,
    "thickness_in_R20": 4.26,
    "thickness_mm_R20": 108,
    "cost_R20_per_m2_usd": 25,
    "non_toxic": "low",
    "foam": "YES",
    "puncture": "some",
    "cuttability": "easy",
    "conform": "no",
    "thermal_bridging": "edge",
    "fire": "poor",
    "moisture": "good (closed cell)",
    "pros": "moisture-resistant, strong",
    "cons": "foam, R-drift, high-GWP blowing agents"
  },
  {
    "name": "PIR / polyiso",
    "category": "foam",
    "r_per_in": 6.2,
    "density_kgm3": 32,
    "cost_per_bf_usd": 0.8,
    "thickness_in_R20": 3.23,
    "thickness_mm_R20": 82,
    "cost_R20_per_m2_usd": 28,
    "non_toxic": "low",
    "foam": "YES",
    "puncture": "some",
    "cuttability": "easy",
    "conform": "no",
    "thermal_bridging": "edge",
    "fire": "char (ok)",
    "moisture": "facer-dependent",
    "pros": "high-R board, cheap, light",
    "cons": "foam; R DROPS in the cold"
  },
  {
    "name": "Phenolic (Kingspan Kooltherm)",
    "category": "foam",
    "r_per_in": 8.0,
    "density_kgm3": 35,
    "cost_per_bf_usd": 2.0,
    "thickness_in_R20": 2.5,
    "thickness_mm_R20": 64,
    "cost_R20_per_m2_usd": 54,
    "non_toxic": "low",
    "foam": "YES",
    "puncture": "some (brittle)",
    "cuttability": "easy but brittle",
    "conform": "no",
    "thermal_bridging": "edge",
    "fire": "good (low smoke)",
    "moisture": "facer-dependent",
    "pros": "best foam R, thin",
    "cons": "foam, brittle, pricey"
  },
  {
    "name": "Spray foam \u2014 closed cell",
    "category": "foam",
    "r_per_in": 6.5,
    "density_kgm3": 35,
    "cost_per_bf_usd": 1.2,
    "thickness_in_R20": 3.08,
    "thickness_mm_R20": 78,
    "cost_R20_per_m2_usd": 40,
    "non_toxic": "iso off-gas",
    "foam": "YES (sprayed)",
    "puncture": "n/a (monolithic)",
    "cuttability": "n/a",
    "conform": "conforms (sprayed)",
    "thermal_bridging": "excellent (monolithic, no gaps)",
    "fire": "ok",
    "moisture": "good",
    "pros": "air-seals everything",
    "cons": "REJECTED (TJ): toxic off-gas, wasteful, imprecise, hard to service"
  },
  {
    "name": "Thinsulate (3M SM600L)",
    "category": "specialty",
    "r_per_in": 3.4,
    "density_kgm3": 6,
    "cost_per_bf_usd": 2.5,
    "thickness_in_R20": 5.88,
    "thickness_mm_R20": 149,
    "cost_R20_per_m2_usd": 158,
    "non_toxic": "yes (hydrophobic)",
    "foam": "no",
    "puncture": "none",
    "cuttability": "easy",
    "conform": "YES (drapes to curves)",
    "thermal_bridging": "good (fills)",
    "fire": "ok",
    "moisture": "hydrophobic \u2014 doesn't hold water",
    "pros": "van-life favorite: non-itch, hydrophobic, acoustic, conforms",
    "cons": "pricey, moderate R, thick"
  },
  {
    "name": "Reflective / radiant barrier (Low-E, Prodex)",
    "category": "specialty",
    "r_per_in": 1.5,
    "density_kgm3": 5,
    "cost_per_bf_usd": 0.6,
    "thickness_in_R20": 13.33,
    "thickness_mm_R20": 339,
    "cost_R20_per_m2_usd": 86,
    "non_toxic": "yes",
    "foam": "no",
    "puncture": "none",
    "cuttability": "easy",
    "conform": "yes",
    "thermal_bridging": "poor (conductive)",
    "fire": "ok",
    "moisture": "vapor barrier",
    "pros": "thin, blocks radiant heat, vapor control",
    "cons": "needs an AIR GAP; low conductive R \u2014 SUPPLEMENT only, not primary"
  },
  {
    "name": "Recycled PET felt",
    "category": "specialty",
    "r_per_in": 3.6,
    "density_kgm3": 30,
    "cost_per_bf_usd": 1.0,
    "thickness_in_R20": 5.56,
    "thickness_mm_R20": 141,
    "cost_R20_per_m2_usd": 60,
    "non_toxic": "yes",
    "foam": "no",
    "puncture": "none",
    "cuttability": "easy",
    "conform": "semi",
    "thermal_bridging": "ok",
    "fire": "ok",
    "moisture": "hydrophobic",
    "pros": "recycled, acoustic, non-toxic",
    "cons": "moderate R, thick"
  },
  {
    "name": "Aerogel blanket (Aspen Spaceloft)",
    "category": "advanced",
    "r_per_in": 10.0,
    "density_kgm3": 150,
    "cost_per_bf_usd": 13.0,
    "thickness_in_R20": 2.0,
    "thickness_mm_R20": 51,
    "cost_R20_per_m2_usd": 280,
    "non_toxic": "yes (dusty when cut)",
    "foam": "no",
    "puncture": "RESILIENT (flexible)",
    "cuttability": "easy (dusty)",
    "conform": "YES \u2014 wraps curves/edges",
    "thermal_bridging": "EXCELLENT (thin wrap kills bridges)",
    "fire": "excellent (-460/+390F)",
    "moisture": "hydrophobic",
    "pros": "densest FLEXIBLE, thin, non-toxic, fireproof, wraps bridges/slide-seals",
    "cons": "VERY pricey per R; dusty to cut"
  },
  {
    "name": "VIP (Panasonic ADVANC-R / va-Q-tec)",
    "category": "advanced",
    "r_per_in": 40.0,
    "density_kgm3": 190,
    "cost_per_bf_usd": 12.0,
    "thickness_in_R20": 0.5,
    "thickness_mm_R20": 13,
    "cost_R20_per_m2_usd": 65,
    "non_toxic": "yes",
    "foam": "no",
    "puncture": "CRITICAL \u2014 a puncture kills the panel",
    "cuttability": "NO \u2014 cannot cut",
    "conform": "NO \u2014 rigid flat only",
    "thermal_bridging": "EDGE bridging (tape/overlap)",
    "fire": "ok",
    "moisture": "sealed",
    "pros": "DENSEST + thinnest R of all; precise panels",
    "cons": "fragile, cannot cut/pierce/fasten-through, ages (~R18 long-term), pricey; flat only"
  }
];
